views_get_payment_gateway_credentials.py:7:0: C0301: Line too long (109/100) (line-too-long)
views_get_payment_gateway_credentials.py:44:0: C0301: Line too long (111/100) (line-too-long)
views_get_payment_gateway_credentials.py:5:0: E0401: Unable to import 'common.apiauthentication.api.authenticateapi.views_authenticateapi' (import-error)
views_get_payment_gateway_credentials.py:6:0: E0401: Unable to import 'common.sessionmanagement.api.sessioncontrol.views_sessioncontrol' (import-error)
views_get_payment_gateway_credentials.py:7:0: E0401: Unable to import 'common.paymentgateways.api.get_payment_gateway_credentials.validations_get_payment_gateway_credentials' (import-error)
views_get_payment_gateway_credentials.py:9:0: E0401: Unable to import 'common.paymentgateways.specificlib.views_lib' (import-error)
views_get_payment_gateway_credentials.py:11:0: C0103: Constant name "logger" doesn't conform to UPPER_CASE naming style (invalid-name)
views_get_payment_gateway_credentials.py:46:15: W0703: Catching too general exception Exception (broad-except)
views_get_payment_gateway_credentials.py:29:4: R0201: Method could be a function (no-self-use)

validations_get_payment_gateway_credentials.py:11:0: C0301: Line too long (103/100) (line-too-long)
validations_get_payment_gateway_credentials.py:12:0: C0301: Line too long (119/100) (line-too-long)
validations_get_payment_gateway_credentials.py:32:15: W0703: Catching too general exception Exception (broad-except)
